# Generated by Django 4.2.2 on 2023-07-06 04:41

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "photo_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=application.models.getFileName
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.category",
                    ),
                ),
            ],
        ),
    ]
